
const programmers = [
  { id:'ahmed',   name:'أحمد الكحلوت',          role:'Frontend Developer',  bio:'صاحب هذا المشروع — بنى Gaza OS من الصفر ليقول: غزة لا تزال تكتب الكود.', email:'ahmed@pcit.gr',    github:'github.com/ahmed-kahlout', skills:['HTML5','CSS3','JavaScript','Responsive Design'], owner:true,  color:'#f0c040', projects:['Gaza OS — هذا الموقع','Portfolio شخصي احترافي'] },
  { id:'qusai',   name:'قصي خضير',               role:'Frontend Developer',  bio:'لم تسكت أصابعه عن لوحة المفاتيح يوماً واحداً رغم كل شيء.',             email:'qusai@pcit.gr',   github:'github.com/qusai',         skills:['HTML','CSS','JavaScript','UI Design'],           owner:false, color:'#5dcaa5', projects:['متجر إلكتروني','لوحة إدارة Dashboard'] },
  { id:'mnaji',   name:'محمد ناجي أبو القمبز',   role:'Frontend Developer',  bio:'الكود لغته والصمود هويته.',                                              email:'mnaji@pcit.gr',   github:'github.com/mnaji',         skills:['HTML','CSS','JS','Flexbox','Grid'],              owner:false, color:'#9fe1cb', projects:['تطبيق مهام تفاعلي','موقع مطعم'] },
  { id:'mfanana', name:'محمد فنانة',              role:'Frontend Developer',  bio:'يصنع المستقبل بسطر واحد في كل مرة.',                                     email:'mfanana@pcit.gr', github:'github.com/mfanana',        skills:['HTML','CSS','JavaScript','Canvas API'],          owner:false, color:'#85b7eb', projects:['لعبة Canvas بالـ JS','Portfolio مميز'] },
  { id:'motasem', name:'معتصم أبو شملة',          role:'Frontend Developer',  bio:'برمجة تحت النار — هذا ما يعني أن تكون غزياً.',                           email:'motasem@pcit.gr', github:'github.com/motasem',        skills:['HTML','CSS','JS','Animations','DOM'],            owner:false, color:'#afa9ec', projects:['موقع تعليمي','Infographic ديناميكي'] },
  { id:'sara',    name:'سارة أبو عمر',            role:'Frontend Developer',  bio:'أثبتت أن المرأة الغزية تبني التكنولوجيا.',                               email:'sara@pcit.gr',    github:'github.com/sara',          skills:['HTML','CSS','JS','UX Design'],                   owner:false, color:'#ed93b1', projects:['واجهة تتبع الصحة','منصة عمل تطوعي'] },
  { id:'yousef',  name:'يوسف الحلو',              role:'Frontend Developer',  bio:'حين تنقطع الكهرباء، يكمل في المخيلة.',                                   email:'yousef@pcit.gr',  github:'github.com/yousef',        skills:['HTML','CSS','JavaScript','LocalStorage'],        owner:false, color:'#ef9f27', projects:['عرض أعمال تفاعلي','Calculator متقدم'] },
  { id:'rana',    name:'رنا السيد',               role:'Frontend Developer',  bio:'كودها رسالتها للعالم الذي لم يسمعهم.',                                   email:'rana@pcit.gr',    github:'github.com/rana',          skills:['HTML','CSS','JS','Responsive','Figma'],          owner:false, color:'#d4537e', projects:['منصة تواصل غزاوي','واجهة Newsletter'] },
  { id:'omar',    name:'عمر النجار',              role:'Frontend Developer',  bio:'لن يُوقف القصفُ الـ commit التالي.',                                     email:'omar@pcit.gr',    github:'github.com/omar',          skills:['HTML','CSS','JS','Git','Animations'],            owner:false, color:'#5dcaa5', projects:['Docs site منظّم','Music player بالـ JS'] },
  { id:'lina',    name:'لينا الشريف',             role:'Frontend Developer',  bio:'Frontend هي لغتها وغزة وطنها.',                                         email:'lina@pcit.gr',    github:'github.com/lina',          skills:['HTML','CSS','JS','CSS Animations'],              owner:false, color:'#9fe1cb', projects:['Gallery تفاعلي','Contact form ذكي'] },
  { id:'khaled',  name:'خالد الغول',              role:'Frontend Developer',  bio:'من هنا يبني ما هدموه بأيدي الكود.',                                     email:'khaled@pcit.gr',  github:'github.com/khaled',        skills:['HTML','CSS','JS','APIs','Fetch'],                owner:false, color:'#85b7eb', projects:['Weather app مع API','Dictionary تفاعلي'] },
  { id:'nour',    name:'نور حمدان',               role:'Frontend Developer',  bio:'كل مشروع أنجزته هو صرخة حياة.',                                        email:'nour@pcit.gr',    github:'github.com/nour',          skills:['HTML','CSS','JS','Forms','Validation'],          owner:false, color:'#ed93b1', projects:['Wedding site أنيق','Booking UI'] },
  { id:'iyad',    name:'إياد رضوان',              role:'Frontend Developer',  bio:'الخوارزميات لا تعرف الحصار.',                                           email:'iyad@pcit.gr',    github:'github.com/iyad',          skills:['HTML','CSS','JS','Algorithms','Canvas'],         owner:false, color:'#afa9ec', projects:['Physics simulation','Data visualization'] },
  { id:'dina',    name:'دينا مطر',                role:'Frontend Developer',  bio:'تُعيد برمجة الأمل سطراً سطراً.',                                        email:'dina@pcit.gr',    github:'github.com/dina',          skills:['HTML','CSS','JS','Accessibility'],               owner:false, color:'#d4537e', projects:['School website كامل','Quran reader UI'] },
  { id:'basel',   name:'باسل الكحلوت',            role:'Frontend Developer',  bio:'العائلة تُبرمج وغزة تنهض.',                                            email:'basel@pcit.gr',   github:'github.com/basel',         skills:['HTML','CSS','JS','UI','Tailwind'],               owner:false, color:'#f0c040', projects:['Corporate site احترافي','Stats dashboard'] },
];